{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "Application",
    "query": {}
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {}
   },
   {
    "name": "service",
    "label": "Service",
    "query": {}
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Service execution performance",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"$app\", env=\"$environment\", instance=~\"($instance)\", service=~\"($service)\"} |= `\"level\":\"trace\"` |= \"Service execute\" | json"
    },
    {
     "expr": "{app=\"$app\", env=\"$environment\", instance=~\"($instance)\", service=~\"($service)\"} |= `\"level\":\"trace\"` |= \"Send service response\" | json"
    }
   ]
  },
  {
   "title": "Service call performances",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"$app\", env=\"$environment\", instance=~\"($instance)\", service=~\"($service)\"} |= `\"level\":\"trace\"` |= `Service call` | json target=\"details.service\", target_method=\"details.method\", message, tid=\"details.tid\" | label_format source=\"{{.service}}\" | label_format id=\"{{.service}}-{{.target}}-{{.mainstat}}\""
    },
    {
     "expr": "{app=\"$app\", env=\"$environment\", instance=~\"($instance)\", service=~\"($service)\"} |= `\"level\":\"trace\"` |= `Service response received` | json target=\"details.service\", target_method=\"details.method\", message, tid=\"details.tid\" | label_format source=\"{{.service}}\" | label_format id=\"{{.service}}-{{.target}}-{{.mainstat}}\""
    }
   ]
  },
  {
   "title": "Latest errors",
   "type": "table",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{app=\"$app\", env=\"$environment\", instance=~\"($instance)\", service=~\"($service)\"} |= `\"level\":\"error\"` | json"
    }
   ]
  }
 ]
}