{
 "title": "Service",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "Application",
    "query": {}
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {}
   },
   {
    "name": "service",
    "label": "Service",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Error ratio",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Success/Errors",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(count_over_time({service=\"$service\", app=\"$app\", env=\"$environment\"} |= `\"level\":\"trace\"` |= `Send service response` [$__interval]))",
     "legendFormat": "Success",
     "resolution": 1
    },
    {
     "expr": "sum(count_over_time({service=\"$service\", app=\"$app\", env=\"$environment\"} |= `Service call error` [$__interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Number of instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{app=\"$app\", env=\"$environment\", service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{service=\"$service\", app=\"$app\", env=\"$environment\"} |= `\"level\":\"trace\"` | json message, tid | message = `Service execute`"
    },
    {
     "expr": "{app=\"$app\", service=\"$service\", env=\"$environment\"} |= `\"level\":\"trace\"` | json message, tid | message = `Send service response`"
    }
   ]
  },
  {
   "title": "Performances",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{app=\"$app\", env=\"$environment\", service=\"$service\"} |= `\"level\":\"trace\"` |= `Service execute` | json target_service=\"details.service\", target_method=\"details.method\", tid"
    },
    {
     "expr": "{app=\"$app\", env=\"$environment\"} |= `\"level\":\"trace\"` |= `Send service response` | json target_service=\"details.service\", target_method=\"details.method\", tid"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 14, "w": 13, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "{app=\"$app\", service=\"$service\", env=\"$environment\"} != `\"level\":\"trace\"` | json level, message, tid=\"details.tid\", details=\"details\""
    }
   ]
  },
  {
   "title": "Dependencies",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{app=\"$app\", env=\"$environment\", service=\"$service\"} |= `\"level\":\"trace\"` |= `Service call` | json target_service=\"details.service\", target_method=\"details.method\", tid=\"details.tid\""
    },
    {
     "expr": "{app=\"$app\", env=\"$environment\"} |= `\"level\":\"trace\"` |= `Service response received` | json target_service=\"details.service\", target_method=\"details.method\", tid=\"details.tid\""
    },
    {
     "expr": "{app=\"$app\", env=\"$environment\"} |= `\"level\":\"error\"` |= `Service call error` | json target_service=\"details.error.details.service\", target_method=\"details.error.details.method\", tid=\"details.tid\""
    }
   ]
  }
 ]
}